export default function Dashboard() {
  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "8rem 8%",
        color: "white",
      }}
    >
      {/* Header */}
      <div
        style={{
          marginBottom: "3rem",
        }}
      >
        <span
          style={{
            color: "#00ff66",
            fontWeight: 600,
          }}
        >
          SECURITY OVERVIEW
        </span>

        <h1
          style={{
            fontSize: "3.5rem",
            marginTop: "1rem",
          }}
        >
          Threat Dashboard
        </h1>

        <p
          style={{
            color: "#9ca3af",
            maxWidth: "700px",
          }}
        >
          Monitor scans, threat levels, and security
          intelligence generated by SentinelForge AI.
        </p>
      </div>

      {/* Stats */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns:
            "repeat(auto-fit,minmax(220px,1fr))",
          gap: "1.5rem",
          marginBottom: "3rem",
        }}
      >
        {[
          {
            title: "Emails Scanned",
            value: "1,248",
            color: "#00ff66",
          },
          {
            title: "URLs Scanned",
            value: "834",
            color: "#00ff66",
          },
          {
            title: "Threats Detected",
            value: "127",
            color: "#ff4d4d",
          },
          {
            title: "Detection Rate",
            value: "94%",
            color: "#ffaa00",
          },
        ].map((item) => (
          <div
            key={item.title}
            style={{
              padding: "1.5rem",
              borderRadius: "20px",
              background: "#0b0b0b",
              border: "1px solid #222",
            }}
          >
            <p
              style={{
                color: "#9ca3af",
              }}
            >
              {item.title}
            </p>

            <h2
              style={{
                color: item.color,
                marginTop: "1rem",
              }}
            >
              {item.value}
            </h2>
          </div>
        ))}
      </div>

      {/* Recent Threats */}
      <div
        style={{
          border: "1px solid #222",
          borderRadius: "20px",
          padding: "2rem",
          background: "#0b0b0b",
          marginBottom: "2rem",
        }}
      >
        <h2>Recent Threats</h2>

        <table
          style={{
            width: "100%",
            marginTop: "1.5rem",
          }}
        >
          <thead>
            <tr>
              <th align="left">Type</th>
              <th align="left">Threat</th>
              <th align="left">Severity</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td>Email</td>
              <td>Phishing Attempt</td>
              <td style={{ color: "#ff4d4d" }}>
                HIGH
              </td>
            </tr>

            <tr>
              <td>URL</td>
              <td>Malicious Domain</td>
              <td style={{ color: "#ffaa00" }}>
                MEDIUM
              </td>
            </tr>

            <tr>
              <td>Email</td>
              <td>Spam Campaign</td>
              <td style={{ color: "#00ff66" }}>
                LOW
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* AI Insights */}
      <div
        style={{
          border: "1px solid rgba(0,255,102,0.2)",
          borderRadius: "20px",
          padding: "2rem",
          background: "#0b0b0b",
        }}
      >
        <h2
          style={{
            color: "#00ff66",
          }}
        >
          AI Insights
        </h2>

        <ul
          style={{
            marginTop: "1rem",
            display: "flex",
            flexDirection: "column",
            gap: "1rem",
          }}
        >
          <li>
            Increase in phishing activity detected
            this week.
          </li>

          <li>
            Most malicious URLs use uncommon TLDs.
          </li>

          <li>
            Email threats account for 68% of
            detections.
          </li>
        </ul>
      </div>
    </main>
  );
}